let ABC_ENG = [
    { letter: 'a', color: 'red' },
    { letter: 'b', color: 'blue' },
    { letter: 'c', color: 'blue' },
    { letter: 'd', color: 'blue' },
    { letter: 'e', color: 'red' },
    { letter: 'f', color: 'blue' },
    { letter: 'g', color: 'blue' },
    { letter: 'h', color: 'blue' },
    { letter: 'i', color: 'red' },
    { letter: 'j', color: 'red' },
    { letter: 'k', color: 'blue' },
    { letter: 'l', color: 'blue' },
    { letter: 'm', color: 'blue' },
    { letter: 'n', color: 'blue' },
    { letter: 'o', color: 'red' },
    { letter: 'p', color: 'blue' },
    { letter: 'q', color: 'blue' },
    { letter: 'r', color: 'blue' },
    { letter: 's', color: 'blue' },
    { letter: 't', color: 'blue' },
    { letter: 'u', color: 'red' },
    { letter: 'v', color: 'blue' },
    { letter: 'w', color: 'blue' },
    { letter: 'x', color: 'blue' },
    { letter: 'y', color: 'red' },
    { letter: 'z', color: 'blue' }
];